### PR TITLE
Remove duplication in utils/colors.rb

### PR DESCRIPTION
**Pull request by OrelSokolov**

### CODE REVIEW

**Comment by a2ikm** [comment]
nice work :+1:

**Comment by okeefm** [comment]
Looks good to me :+1:

**Comment by dankohn** [comment]
This works well for me with Ruby 2.2. It can be accessed now with:

```ruby
 gem 'ruby-graphviz', github: 'OrelSokolov/Ruby-Graphviz', ref: '6402f01
```

**Comment by pokonski** [comment]
@glejeune can you merge this and releaase the new version? This is extremely annoying as it spams everything, from tests output in host apps to production.

**Comment by codebender** [comment]
Possibly we can get Grégoire's attention on Twitter? https://twitter.com/glejeune

**Comment by pokonski** [comment]
Perfect, thanks @glejeune :fireworks:

**Comment by codebender** [comment]
:clap: :100:

**Pull request merged**
