### PR TITLE
Remove duplicated keys

### PR DESCRIPTION
**Pull request by incubus**
Fix ruby 2.2 warnings about the duplicated key. Five keys "gray, grey, green, maroon, purple" should be fixed manually by author as they has different values in the hash. Thanks!

### CODE REVIEW

**Comment by jesperronn** [comment]
Is there anything we can do to get a ruby 2.2-friendly release out of the door?

**Comment by dg-ratiodata** [comment]
@glejeune

Would you mind to release a new version? This one would reduce the noise during rspec runs a  lot.

**Comment by jesperronn** [comment]
:+1:

**Comment by huned** [comment]
@glejeune +1 on releasing a new version please.

**Comment by jbender** [comment]
:+1:

**Comment by hopsoft** [comment]
+1

**Comment by dankohn** [comment]
Pull request https://github.com/glejeune/Ruby-Graphviz/pull/103 fixes all color values when running under Ruby 2.2. You can access it now with:

```ruby
 gem 'ruby-graphviz', github: 'OrelSokolov/Ruby-Graphviz', ref: '6402f01
```

**Comment by lbeder** [comment]
:+1:

**Comment by jeremywadsack** [comment]
A new release, please.

**Comment by codebender** [comment]
@glejeune S'il vous plaît :+1:

**Comment by a2ikm** [comment]
This seems fixed with #103 and v1.2.2 :)

**Comment by AknEp** [comment]
+1

**Pull request closed without merging**
