### PR TITLE
Add license to gemspec

### PR DESCRIPTION
**Pull request by codegoalie**
I was trying to determine the licenses for my dependencies. I found that the RubyGems API will return the license, but only if it is specified in your gemspec file.

### CODE REVIEW

**Comment by bvogel** [comment]
If I read the README.rdoc correctly that would be GNU GPL, the included nothugly.xsl uses MIT.

**Comment by chrismar035** [comment]
Good catch. I updated this commit.

**Comment by shaneog** [comment]
Doesn't this commit make the gem dual licensed under both MIT and GPL-2?
_As I understand it_, the spec `licenses` is for the licenses that apply to the gem/library, and not to those of sub-components.

**Comment by olleolleolle** [comment]
The license information for GPL-2.0 was added to the gemspec 7 months ago: https://github.com/glejeune/Ruby-Graphviz/commit/5f5131fb7e6200030f6c042f42744d314baba5ad

This issue can now be closed.

**Pull request closed without merging**
